spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram-bot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
